# -*- Makefile -*-
# $Id: Makefile,v 1.2 2019/08/2 19:25:32 mpall Exp $
# $Copyright: (c) 2005 Broadcom Corp.
# All Rights Reserved.$
# Added by rpr

SDK :=$(shell if [ -n "$$SDK" ] ; then\
	echo $$SDK;\
	else\
	cd $(dir $(lastword $(MAKEFILE_LIST))); while /usr/bin/test ! -e RELEASE ; do \
	dir=`cd ../;pwd`;			\
	if [ "$$dir" = "/" ] ; then		\
	   echo Cannot find SDK in $(lastword $(MAKEFILE_LIST)) 1>&2;		\
	   exit 1;				\
	fi ;					\
	cd $$dir;				\
	done ;					\
	pwd;					\
	fi)

ifeq ($(SDK),)
$(error Please run this in a tree)
endif 

export SDK

override kernel_version=5_10
platform=arm64-ls1046a

#export MAKE_LOCAL=${SDK}/make/Make.linux-${platform}
export BUILD_PLATFORM
export ARM_LINUX_VERSION
export ADD_TO_CFLAGS
export BR_NO_CCACHE

LINUX_MAKE_USER=1
include ${SDK}/make/Make.linux
